import {pgTable,uuid,varchar,text,integer,boolean,timestamp,primaryKey,index} from "drizzle-orm/pg-core";
const id=()=>uuid("id").defaultRandom().primaryKey();
export const users=pgTable("users",{id:id(),email:varchar("email",{length:320}).notNull().unique(),displayName:varchar("display_name",{length:120}).notNull(),passwordHash:text("password_hash"),createdAt:timestamp("created_at",{withTimezone:true}).defaultNow().notNull(),updatedAt:timestamp("updated_at",{withTimezone:true}).defaultNow().notNull()});
export const sessions=pgTable("sessions",{id:id(),userId:uuid("user_id").notNull().references(()=>users.id,{onDelete:"cascade"}),tokenHash:text("token_hash").notNull().unique(),expiresAt:timestamp("expires_at",{withTimezone:true}).notNull(),revokedAt:timestamp("revoked_at",{withTimezone:true}),createdAt:timestamp("created_at",{withTimezone:true}).defaultNow().notNull()},t=>({userIdx:index("sessions_user_idx").on(t.userId)}));
export const projects=pgTable("projects",{id:id(),userId:uuid("user_id").notNull().references(()=>users.id,{onDelete:"cascade"}),parentId:uuid("parent_id"),name:varchar("name",{length:200}).notNull(),description:text("description"),color:varchar("color",{length:32}),icon:varchar("icon",{length:64}),favorite:boolean("favorite").default(false).notNull(),archived:boolean("archived").default(false).notNull(),position:integer("position").default(0).notNull(),createdAt:timestamp("created_at",{withTimezone:true}).defaultNow().notNull(),updatedAt:timestamp("updated_at",{withTimezone:true}).defaultNow().notNull()},t=>({userIdx:index("projects_user_idx").on(t.userId)}));
export const sections=pgTable("sections",{id:id(),projectId:uuid("project_id").notNull().references(()=>projects.id,{onDelete:"cascade"}),name:varchar("name",{length:200}).notNull(),position:integer("position").default(0).notNull(),createdAt:timestamp("created_at",{withTimezone:true}).defaultNow().notNull(),updatedAt:timestamp("updated_at",{withTimezone:true}).defaultNow().notNull()});
export const tasks=pgTable("tasks",{id:id(),userId:uuid("user_id").notNull().references(()=>users.id,{onDelete:"cascade"}),parentTaskId:uuid("parent_task_id"),projectId:uuid("project_id").references(()=>projects.id,{onDelete:"set null"}),sectionId:uuid("section_id").references(()=>sections.id,{onDelete:"set null"}),title:varchar("title",{length:500}).notNull(),description:text("description"),priority:integer("priority").default(4).notNull(),status:varchar("status",{length:20}).default("active").notNull(),dueAt:timestamp("due_at",{withTimezone:true}),deadlineAt:timestamp("deadline_at",{withTimezone:true}),durationMinutes:integer("duration_minutes"),recurrence:text("recurrence"),position:varchar("position",{length:100}).default("a0").notNull(),completedAt:timestamp("completed_at",{withTimezone:true}),deletedAt:timestamp("deleted_at",{withTimezone:true}),createdAt:timestamp("created_at",{withTimezone:true}).defaultNow().notNull(),updatedAt:timestamp("updated_at",{withTimezone:true}).defaultNow().notNull()},t=>({userIdx:index("tasks_user_idx").on(t.userId),projectIdx:index("tasks_project_idx").on(t.projectId),statusIdx:index("tasks_status_idx").on(t.status)}));
export const labels=pgTable("labels",{id:id(),userId:uuid("user_id").notNull().references(()=>users.id,{onDelete:"cascade"}),name:varchar("name",{length:100}).notNull(),color:varchar("color",{length:32}),description:text("description"),favorite:boolean("favorite").default(false).notNull(),createdAt:timestamp("created_at",{withTimezone:true}).defaultNow().notNull(),updatedAt:timestamp("updated_at",{withTimezone:true}).defaultNow().notNull()});
export const taskDependencies=pgTable("task_dependencies",{taskId:uuid("task_id").notNull().references(()=>tasks.id,{onDelete:"cascade"}),dependsOnTaskId:uuid("depends_on_task_id").notNull().references(()=>tasks.id,{onDelete:"cascade"}),createdAt:timestamp("created_at",{withTimezone:true}).defaultNow().notNull()},t=>({pk:primaryKey({columns:[t.taskId,t.dependsOnTaskId]})}));
export const taskLabels=pgTable("task_labels",{taskId:uuid("task_id").notNull().references(()=>tasks.id,{onDelete:"cascade"}),labelId:uuid("label_id").notNull().references(()=>labels.id,{onDelete:"cascade"})},t=>({pk:primaryKey({columns:[t.taskId,t.labelId]})}));

export const reminders=pgTable("reminders",{id:id(),userId:uuid("user_id").notNull().references(()=>users.id,{onDelete:"cascade"}),taskId:uuid("task_id").notNull().references(()=>tasks.id,{onDelete:"cascade"}),trigger:varchar("trigger",{length:32}).notNull(),triggerAt:timestamp("trigger_at",{withTimezone:true}),minutesBefore:integer("minutes_before"),locationId:varchar("location_id",{length:200}),recurringRule:text("recurring_rule"),enabled:boolean("enabled").default(true).notNull(),createdAt:timestamp("created_at",{withTimezone:true}).defaultNow().notNull()});
export const comments=pgTable("comments",{id:id(),userId:uuid("user_id").notNull().references(()=>users.id,{onDelete:"cascade"}),taskId:uuid("task_id").references(()=>tasks.id,{onDelete:"cascade"}),projectId:uuid("project_id").references(()=>projects.id,{onDelete:"cascade"}),body:text("body").notNull(),createdAt:timestamp("created_at",{withTimezone:true}).defaultNow().notNull(),updatedAt:timestamp("updated_at",{withTimezone:true}).defaultNow().notNull(),deletedAt:timestamp("deleted_at",{withTimezone:true})});
export const automationExecutions=pgTable("automation_executions",{id:id(),ruleId:uuid("rule_id").notNull().references(()=>automationRules.id,{onDelete:"cascade"}),eventId:varchar("event_id",{length:200}).notNull(),status:varchar("status",{length:32}).notNull(),attempts:integer("attempts").default(0).notNull(),createdAt:timestamp("created_at",{withTimezone:true}).defaultNow().notNull(),completedAt:timestamp("completed_at",{withTimezone:true})});
export const projectMembers=pgTable("project_members",{projectId:uuid("project_id").notNull().references(()=>projects.id,{onDelete:"cascade"}),userId:uuid("user_id").notNull().references(()=>users.id,{onDelete:"cascade"}),role:varchar("role",{length:32}).notNull(),addedAt:timestamp("added_at",{withTimezone:true}).defaultNow().notNull()},t=>({pk:primaryKey({columns:[t.projectId,t.userId]})}));
export const attachments=pgTable("attachments",{id:id(),userId:uuid("user_id").notNull().references(()=>users.id,{onDelete:"cascade"}),taskId:uuid("task_id").references(()=>tasks.id,{onDelete:"cascade"}),commentId:uuid("comment_id").references(()=>comments.id,{onDelete:"cascade"}),fileName:varchar("file_name",{length:255}).notNull(),mimeType:varchar("mime_type",{length:150}).notNull(),sizeBytes:integer("size_bytes").notNull(),storageKey:text("storage_key").notNull(),createdAt:timestamp("created_at",{withTimezone:true}).defaultNow().notNull()});
export const workspaces=pgTable("workspaces",{id:id(),ownerId:uuid("owner_id").notNull().references(()=>users.id,{onDelete:"cascade"}),name:varchar("name",{length:200}).notNull(),createdAt:timestamp("created_at",{withTimezone:true}).defaultNow().notNull(),updatedAt:timestamp("updated_at",{withTimezone:true}).defaultNow().notNull()});
export const workspaceMembers=pgTable("workspace_members",{workspaceId:uuid("workspace_id").notNull().references(()=>workspaces.id,{onDelete:"cascade"}),userId:uuid("user_id").notNull().references(()=>users.id,{onDelete:"cascade"}),role:varchar("role",{length:32}).notNull(),createdAt:timestamp("created_at",{withTimezone:true}).defaultNow().notNull()},t=>({pk:primaryKey({columns:[t.workspaceId,t.userId]})}));
export const goals=pgTable("goals",{id:id(),userId:uuid("user_id").notNull().references(()=>users.id,{onDelete:"cascade"}),name:varchar("name",{length:200}).notNull(),period:varchar("period",{length:32}).notNull(),target:integer("target").notNull(),progress:integer("progress").default(0).notNull(),startsAt:timestamp("starts_at",{withTimezone:true}).notNull(),endsAt:timestamp("ends_at",{withTimezone:true}).notNull(),createdAt:timestamp("created_at",{withTimezone:true}).defaultNow().notNull()});
export const automationRules=pgTable("automation_rules",{id:id(),ownerId:uuid("owner_id").notNull().references(()=>users.id,{onDelete:"cascade"}),name:varchar("name",{length:200}).notNull(),trigger:varchar("trigger",{length:64}).notNull(),conditions:text("conditions").notNull(),actions:text("actions").notNull(),enabled:boolean("enabled").default(true).notNull(),createdAt:timestamp("created_at",{withTimezone:true}).defaultNow().notNull()});
export const templates=pgTable("templates",{id:id(),ownerId:uuid("owner_id").notNull().references(()=>users.id,{onDelete:"cascade"}),name:varchar("name",{length:200}).notNull(),description:text("description"),scope:varchar("scope",{length:32}).notNull(),visibility:varchar("visibility",{length:32}).notNull(),version:integer("version").default(1).notNull(),contentJson:text("content_json").notNull(),createdAt:timestamp("created_at",{withTimezone:true}).defaultNow().notNull(),updatedAt:timestamp("updated_at",{withTimezone:true}).defaultNow().notNull()});
export const devices=pgTable("devices",{id:id(),userId:uuid("user_id").notNull().references(()=>users.id,{onDelete:"cascade"}),platform:varchar("platform",{length:32}).notNull(),name:varchar("name",{length:120}),pushToken:text("push_token"),lastSeenAt:timestamp("last_seen_at",{withTimezone:true}).defaultNow().notNull(),revokedAt:timestamp("revoked_at",{withTimezone:true})});
export const apiTokens=pgTable("api_tokens",{id:id(),ownerId:uuid("owner_id").notNull().references(()=>users.id,{onDelete:"cascade"}),name:varchar("name",{length:100}).notNull(),tokenHash:text("token_hash").notNull().unique(),scopes:text("scopes").notNull(),createdAt:timestamp("created_at",{withTimezone:true}).defaultNow().notNull(),revokedAt:timestamp("revoked_at",{withTimezone:true})});

export const syncState=pgTable("sync_state",{userId:uuid("user_id").primaryKey().references(()=>users.id,{onDelete:"cascade"}),revision:integer("revision").default(0).notNull(),updatedAt:timestamp("updated_at",{withTimezone:true}).defaultNow().notNull()});
export const syncOperations=pgTable("sync_operations",{operationId:varchar("operation_id",{length:200}).primaryKey(),userId:uuid("user_id").notNull().references(()=>users.id,{onDelete:"cascade"}),revision:integer("revision").notNull(),createdAt:timestamp("created_at",{withTimezone:true}).defaultNow().notNull()},t=>({userRevisionIdx:index("sync_operations_user_revision_idx").on(t.userId,t.revision)}));
