import type {FastifyInstance} from "fastify";
import crypto from "node:crypto";
import {z} from "zod";
import {requireScope} from "./require-auth";
import {createReminder,listReminders} from "../../../packages/db/src/reminder-repository";
import {insertComment,listTaskComments} from "../../../packages/db/src/repositories";
import {listAutomationRules,createAutomationRule} from "../../../packages/db/src/automation-repository";
import {insertWorkspace,listWorkspaces} from "../../../packages/db/src/repositories";
const reminderSchema=z.object({taskId:z.string().uuid(),trigger:z.string().min(1).max(32),triggerAt:z.string().datetime().nullable().optional(),minutesBefore:z.number().int().min(0).max(525600).nullable().optional(),locationId:z.string().max(200).nullable().optional(),recurringRule:z.string().max(1000).nullable().optional(),enabled:z.boolean().optional()});
const automationSchema=z.object({name:z.string().trim().min(1).max(200),trigger:z.string().min(1).max(200),conditions:z.array(z.unknown()).default([]),actions:z.array(z.unknown()).min(1),enabled:z.boolean().optional()});
const workspaceSchema=z.object({name:z.string().trim().min(1).max(200)});
export function registerResourceRoutes(app:FastifyInstance){
 app.get("/api/v1/reminders",async(req,reply)=>{try{const u=await requireScope(req,"reminders:read");return listReminders(u.id);}catch(e){return reply.code(401).send({error:e instanceof Error?e.message:"Authentication required"});}});
 app.post("/api/v1/reminders",async(req,reply)=>{try{const u=await requireScope(req,"reminders:write");const b=reminderSchema.parse(req.body);const item=await createReminder({id:crypto.randomUUID(),userId:u.id,taskId:b.taskId,trigger:b.trigger,triggerAt:b.triggerAt?new Date(b.triggerAt):null,minutesBefore:b.minutesBefore??null,locationId:b.locationId??null,recurringRule:b.recurringRule??null,enabled:b.enabled!==false});return reply.code(201).send(item);}catch(e){return reply.code(e instanceof Error&&e.message.startsWith("API token lacks")?403:400).send({error:e instanceof Error?e.message:"Invalid reminder"});}});
 app.get("/api/v1/comments/:taskId",async(req,reply)=>{try{const u=await requireScope(req,"comments:read");const {taskId}=z.object({taskId:z.string().uuid()}).parse(req.params);return listTaskComments(taskId,u.id);}catch(e){return reply.code(401).send({error:e instanceof Error?e.message:"Authentication required"});}});
 app.post("/api/v1/comments/:taskId",async(req,reply)=>{try{const u=await requireScope(req,"comments:write");const {taskId}=z.object({taskId:z.string().uuid()}).parse(req.params);const b=z.object({body:z.string().trim().min(1).max(20000)}).parse(req.body);const item=await insertComment({id:crypto.randomUUID(),userId:u.id,taskId,body:b.body});return reply.code(201).send(item);}catch(e){return reply.code(e instanceof Error&&e.message.startsWith("API token lacks")?403:400).send({error:e instanceof Error?e.message:"Invalid comment"});}});
 app.get("/api/v1/automations",async(req,reply)=>{try{const u=await requireScope(req,"automations:read");return listAutomationRules(u.id);}catch(e){return reply.code(401).send({error:e instanceof Error?e.message:"Authentication required"});}});
 app.post("/api/v1/automations",async(req,reply)=>{try{const u=await requireScope(req,"automations:write");const b=automationSchema.parse(req.body);const item=await createAutomationRule({id:crypto.randomUUID(),ownerId:u.id,name:b.name,trigger:b.trigger,conditions:b.conditions,actions:b.actions,enabled:b.enabled!==false});return reply.code(201).send(item);}catch(e){return reply.code(e instanceof Error&&e.message.startsWith("API token lacks")?403:400).send({error:e instanceof Error?e.message:"Invalid automation"});}});
 app.get("/api/v1/workspaces",async(req,reply)=>{try{const u=await requireScope(req,"workspaces:read");return listWorkspaces(u.id);}catch(e){return reply.code(401).send({error:e instanceof Error?e.message:"Authentication required"});}});
 app.post("/api/v1/workspaces",async(req,reply)=>{try{const u=await requireScope(req,"workspaces:write");const b=workspaceSchema.parse(req.body);const item=await insertWorkspace({id:crypto.randomUUID(),ownerId:u.id,name:b.name});return reply.code(201).send(item);}catch(e){return reply.code(e instanceof Error&&e.message.startsWith("API token lacks")?403:400).send({error:e instanceof Error?e.message:"Invalid workspace"});}});
}