import type {FastifyInstance} from "fastify";
import { TaskService } from "../../../packages/domain/task-service";
import { PostgresTaskRepository } from "../../../packages/db/src/task-repository";
import {requireScope} from "./require-auth";
import {z} from "zod";
const createSchema=z.object({title:z.string().trim().min(1).max(500),projectId:z.string().uuid().nullable().optional(),description:z.string().max(10000).optional(),parentTaskId:z.string().uuid().nullable().optional(),sectionId:z.string().uuid().nullable().optional(),priority:z.enum(["P1","P2","P3","P4"]).optional(),dueAt:z.string().datetime().nullable().optional(),deadlineAt:z.string().datetime().nullable().optional(),durationMinutes:z.number().int().min(0).max(1440).nullable().optional(),recurrence:z.string().max(1000).nullable().optional(),position:z.string().max(100).optional()});
const updateSchema=createSchema.partial();
export function registerTaskRoutes(app:FastifyInstance){const repository=new PostgresTaskRepository();const service=new TaskService(repository);
 app.post("/api/v1/tasks",async(request,reply)=>{try{const user=await requireScope(request,"tasks:write");const body=createSchema.parse(request.body);return reply.code(201).send(await service.create({...body,userId:user.id}));}catch(error){return reply.code(error instanceof Error&&error.message.startsWith("API token lacks")?403:400).send({error:error instanceof Error?error.message:"Invalid task"});}});
 app.get("/api/v1/tasks",async(request,reply)=>{try{const user=await requireScope(request,"tasks:read");return service.repositoryList(user.id);}catch(error){return reply.code(error instanceof Error&&error.message.startsWith("API token lacks")?403:401).send({error:error instanceof Error?error.message:"Authentication required"});}});
 app.patch("/api/v1/tasks/:id",async(request,reply)=>{try{const user=await requireScope(request,"tasks:write");const params=z.object({id:z.string().uuid()}).parse(request.params);const body=updateSchema.parse(request.body);return reply.send(await service.update(user.id,params.id,body));}catch(error){return reply.code(error instanceof Error&&error.message.startsWith("API token lacks")?403:400).send({error:error instanceof Error?error.message:"Invalid task update"});}});
 app.post("/api/v1/tasks/:id/complete",async(request,reply)=>{try{const user=await requireScope(request,"tasks:write");const {id}=z.object({id:z.string().uuid()}).parse(request.params);return reply.send(await service.complete(user.id,id));}catch(error){return reply.code(error instanceof Error&&error.message.startsWith("API token lacks")?403:400).send({error:error instanceof Error?error.message:"Unable to complete task"});}});
 app.post("/api/v1/tasks/:id/reopen",async(request,reply)=>{try{const user=await requireScope(request,"tasks:write");const {id}=z.object({id:z.string().uuid()}).parse(request.params);return reply.send(await service.reopen(user.id,id));}catch(error){return reply.code(error instanceof Error&&error.message.startsWith("API token lacks")?403:400).send({error:error instanceof Error?error.message:"Unable to reopen task"});}});
 app.post("/api/v1/tasks/:id/restore",async(request,reply)=>{try{const user=await requireScope(request,"tasks:write");const {id}=z.object({id:z.string().uuid()}).parse(request.params);return reply.send(await service.restore(user.id,id));}catch(error){return reply.code(error instanceof Error&&error.message.startsWith("API token lacks")?403:400).send({error:error instanceof Error?error.message:"Unable to restore task"});}});
 app.delete("/api/v1/tasks/:id",async(request,reply)=>{try{const user=await requireScope(request,"tasks:write");const {id}=z.object({id:z.string().uuid()}).parse(request.params);await service.remove(user.id,id);return reply.code(204).send();}catch(error){return reply.code(error instanceof Error&&error.message.startsWith("API token lacks")?403:400).send({error:error instanceof Error?error.message:"Unable to delete task"});}});
}